### PR TITLE
Frontend Error Handling

### LINKED ISSUE #289: Frontend Error Handling
### Context

The way we currently handle and display errors to the user is poor. Here's an example:
- Login as admin and navigate to the student table
- Click edit on one of the students
- Attempt to change the phone number to a phone number taken by another student

Expected behavior:
- The user immediately gets feedback and a clear message that states the phone number conflicts with another student

Actual behavior:
- The error message is printed at the top of the form, requiring the user to know to scroll up to find it
- The error message is unclear: "Failed to update student: Failed to update student"

This is caused by our error handling at the frontend service layer, where (for most services) we map any error to a generic error with a generic message, removing any information that came with the error.

### Completion Criteria

- [ ] All frontend services are updated to preserve the information from the error
- [ ] All places that consume query/service errors are changed to map the error to the correct error message

### Important Notes

-  Do a through audit of the frontend to make sure all cases are covered

### PR DESCRIPTION
**Pull request by aileenr19**
The way we currently handle and display errors to the user is poor and is bad UX. We need clearer error messages.

Changes:
- fixed the bugs by not throwing a new error in the frontend services, and instead throwing the pre-existing error so we can preserve the details

Closes #289.

### CODE REVIEW

**Review by naasanov — CHANGES_REQUESTED** [review]
We sholud update all service functions with the new pattern in order to maintain a consistent interface. Make sure all frontend service functions rethrow. 

It might also be better to get rid of the try catch alltogether since we are rethrowing. Network issues already have clean logging via the devtools network tab, so the logs aren't doing very much.

File: frontend/src/app/staff/_components/party/PartyTable.tsx [hunk 1]
```diff
@@ -65,6 +64,19 @@ const SERVER_COLUMN_MAP: ServerColumnMap = {
...
+    const err = error as unknown as Record<string, unknown>;
+    const detail = (err.response as Record<string, unknown>)?.data as Record<
+      string,
+      unknown
+    >;
+    if (detail?.message) return String(detail.message);
+    if (detail?.detail) return String(detail.detail);
+  } catch {}
+  return "Operation failed";
+};
```
Comment (naasanov) [inline frontend/src/app/staff/_components/party/PartyTable.tsx:87]: You can use the built in function `isAxiosError` instead of doing unsafe casting. This applies to other files

File: frontend/src/app/staff/_components/party/PartyTable.tsx [hunk 2]
```diff
@@ -65,6 +64,19 @@ const SERVER_COLUMN_MAP: ServerColumnMap = {
...
 
+const getErrorMessage = (error: Error): string => {
+  try {
+    const err = error as unknown as Record<string, unknown>;
+    const detail = (err.response as Record<string, unknown>)?.data as Record<
+      string,
+      unknown
+    >;
+    if (detail?.message) return String(detail.message);
+    if (detail?.detail) return String(detail.detail);
```
Comment (naasanov) [inline frontend/src/app/staff/_components/party/PartyTable.tsx:83]: We should not be taking the error message verbatim from the backend. The backend should not be responsible for presentational aspects. Instead we should map the error to the correct error message based on something like the status code. E.g.

pseudocode:
```
switch (error.statusCode) {
  case 409: return "This phone number is already taken by another student" (or smth)
  default: return "Failed to update student"
}
```

**Review by naasanov — CHANGES_REQUESTED** [review]

**Review by naasanov — APPROVED** [review]
LGTM!
