### PR TITLE
Table Form Fixes

### LINKED ISSUE #160: Table Form Fixes
### Motivation

There are several small issues with the Create & Edit forms for admin/staff. This ticket should clean up the rough edges with this feature.

### Deliverables

Fix the following issues
 
  - [x] Phone number regex is not checked on client side, should match the backend regex (party, student) 
  - [x] Many forms do not show the error dialog for server issues (not founds, conflicts, etc.)
    - This is confirmed for edit party and create location, but should be checked for all forms
    - Some will error but look like they succeeded (confirmed for create student but could exist for others). This is likely due to over-optimistic rendering with react query. Feel free to just remove the offending optimistic rendering. There will be a future ticket which will be focused on implementing optimistic rendering in all relevant queries.
  - [x] Many error dialogs are not descriptive (e.g. “Failed to create party: Failed to create party”)
    - Status codes should be mapped to descriptive error messages
  - [x] In edit forms, the address is not pre-loaded into the address search component correctly (party, location)
  - [x] For forms with optional (nullable) fields, it should be made clear that these fields are optional somehow (student : last registered, location : hold expiration date, and any others)
  - [x] Email and PID fields should be made non-editable in edit forms (student, account)
    - This is because these fields are decided by SSO, so editing them would cause problems.
    - They are kept in create forms for extraneous situations
    - In editing forms, the field should still be there with the data visible, but have the input disabled
    - Suggestion: Could implement this by checking if `editData` is non-null, and disabling inputs if so

### Important Notes

- A lot of these errors are from integration with react query which was implemented during HackDay, so issues were expected

### PR DESCRIPTION
**Pull request by aileenr19**
There are several small issues with the Create & Edit forms for admin/staff. This ticket should clean up the rough edges with this feature.

Changes:

- Changed student, party create/edit forms for staff and students, mainly ensuring errors pop up correctly (for phone number, contact preference, etc)
- Made it so the form updates with an error message when submission fails
- Fixed location and party service so it throws the AxiosError so we can get a more detailed error message
- Fixed AddressSearch so that in edit forms the address is pre-loaded
- Added field descriptions to clarify when fields are optional 
- Disabled editing for pid and email if in edit mode

Closes #160.

### CODE REVIEW

File: frontend/src/app/staff/_components/student/StudentTableForm.tsx [hunk 1]
```diff
@@ -31,10 +32,18 @@ export const studentTableFormSchema = z.object({
...
+    .min(1, "Phone number is required"),
+  contact_preference: z.enum(["call", "text"], {
+    message: "Please select a contact preference",
+  }),
   last_registered: z.date().nullable(),
-  pid: z.string().length(9, "Please input a valid PID"),
+  pid: z
+    .string()
+    .length(9, "Please input a valid PID")
+    .min(1, "PID is required"),
```
Comment (naasanov) [inline frontend/src/app/staff/_components/student/StudentTableForm.tsx]: Didn't catch this in my inital bug search but looks like the form doesn't make sure PID is all digits. Will have to change this for accoutn table as well

File: frontend/src/app/staff/_components/location/LocationTable.tsx [hunk 2]
```diff
@@ -36,9 +70,15 @@ export const LocationTable = () => {
   const createMutation = useMutation({
     mutationFn: (payload: LocationCreate) =>
       locationService.createLocation(payload),
-    onError: (error: Error) => {
+    onError: (error: AxiosError<{ message: string }>) => {
+      // Change to any to access response
       console.error("Failed to create location:", error);
-      setSubmissionError(`Failed to create location: ${error.message}`);
+      const errorMessage = error.response?.data?.message || error.message;
+      if (error.response?.data?.message?.includes("Google Place ID")) {
```
Comment (naasanov) [inline frontend/src/app/staff/_components/location/LocationTable.tsx]: Would be more robust to check if status == 409 instead of parsing the message

File: frontend/src/app/staff/_components/location/LocationTable.tsx [hunk 3]
```diff
@@ -51,9 +91,11 @@ export const LocationTable = () => {
   const updateMutation = useMutation({
     mutationFn: ({ id, payload }: { id: number; payload: LocationCreate }) =>
       locationService.updateLocation(id, payload),
-    onError: (error: Error) => {
+    onError: (error: AxiosError<{ message: string }>) => {
+      // Change to any to access response
       console.error("Failed to update location:", error);
-      setSubmissionError(`Failed to update location: ${error.message}`);
+      const errorMessage = error.response?.data?.message || error.message;
+      setSubmissionError(errorMessage);
```
Comment (naasanov) [inline frontend/src/app/staff/_components/location/LocationTable.tsx]: The update should also check for a 409 with a "This location already exists" message

File: frontend/src/app/staff/_components/party/PartyTable.tsx [hunk 4]
```diff
@@ -25,6 +25,34 @@ export const PartyTable = () => {
...
+          "New Party",
+          "Add a new party to the system",
+          <PartyTableForm
+            onSubmit={handleFormSubmit}
+            submissionError={submissionError}
+          />
+        );
+      }
+    }
+  }, [submissionError]);
```
Comment (naasanov) [inline frontend/src/app/staff/_components/party/PartyTable.tsx]: I see how the error is caused now. I don't know if `useEffect` is the right tool this time though. Is it possible to call `openSidebar` directly in the `onError` callback in the mutation or maybe in `handleFormSubmit`? That would make it more directly part of the pipline instead of being decoupled.

**Review by naasanov — CHANGES_REQUESTED** [review]
Thanks for fixing a lot of those errors. I'm still having some issues though.

Unrelated to code, in future when you take care of an error where the cause is unknown could you stick a little blurb in the PR description that explains what caused it? Makes the motivation for some code changes more clear when reading over them.

Thanks!!
