### PR TITLE
Fixed how the pagination UI looks and how much space it takes. Also fixed admin autofill.

### LINKED ISSUE #298: Remove Autofill From Admin Forms
### Motivation

For example, when filling in contact two email when creating a party, it tries to autofill my email. Admins will almost never be putting in their own email, so that can be supressed.

### Deliverables

- Specific thing to implement/fix
- Another deliverable
- etc.

### Important Notes

- Dependencies (e.g., Depends on #XX)
- Implementation constraints or preferences
- Any other context or gotchas

### LINKED ISSUE #299: Lower Pagination UI Footprint
### Motivation

Make pagination UI one row instead of two rows to leave more room for data. While we're at it we can add a better indicator for what the number dropdown does.

### Deliverables

- Specific thing to implement/fix
- Another deliverable
- etc.

### Important Notes

- Dependencies (e.g., Depends on #XX)
- Implementation constraints or preferences
- Any other context or gotchas

### PR DESCRIPTION
**Pull request by manyuagashe**
Pagination UI was taking up two rows of vertical space, reducing the amount of data visible in tables. Additionally, 
  admin forms were autofilling with the admin's own information when creating records for students/parties, which is   
  rarely the intended behavior.                                                                                        
                                                                                                                       
  Changes:                                                                                                             
                                                                                                                       
  - Consolidated pagination controls into a single horizontal row using flexbox flex-row with justify-between spacing  
  - Added "Rows per page:" label to the page size dropdown for better clarity on what the control does                 
  - Added whitespace-nowrap to pagination text elements to prevent line wrapping                                       
  - Disabled browser autofill on all admin form inputs by adding autoComplete="off" to form fields across Account,     
  Party, Student, Incident, and Police Account forms                                                                   
                                                                                                                       
  Closes #299                                                                                                          
  Closes #298

### CODE REVIEW

File: frontend/src/app/staff/_components/account/PoliceAccountForm.tsx [hunk 1]
```diff
@@ -113,6 +114,7 @@ export default function PoliceAccountForm({
               value={formData.password}
               onChange={(e) => updateField("password", e.target.value)}
               aria-invalid={!!errors.password}
+              autoComplete="off"
```
Comment (notvasub) [inline frontend/src/app/staff/_components/account/PoliceAccountForm.tsx]: Cursor noticed the following issue. 

---

When an admin creates a new police account in PoliceAccountForm, there's a password input with `autoComplete="off"`:

The intent is: don't autofill this field with the admin's own saved password. That makes sense.

The problem is that major browsers — Chrome, Firefox, Safari — deliberately ignore autoComplete="off" on type="password" fields. This is by design: browser vendors decided years ago that password managers are too important for security to let developers disable them. So this attribute will simply have no effect on the password input.

The value browsers do respect on password fields is `autoComplete="new-password"`. This tells the browser "this is a field for creating a new account's password, not logging in" — so it won't try to fill it with the admin's own saved credentials, and it also prompts the password manager to save the new password (for the police account being created) rather than the admin's. That's exactly the right semantic here:

`autoComplete="new-password"`

**Review by notvasub — COMMENTED** [review]
I don't know if this is by design or if this is just a general pitfall, i did notice the app's responsiveness like dies the second that you make it any smaller. You aren't able to scroll the white box for events nor see the map or anything and pagination completely disappeared. This could be problematic if it doesn't work on tablet interfaces either so maybe something to look into idk.

https://github.com/user-attachments/assets/f64a3402-11c2-41f9-9d65-5afd2d2687e5

**Comment by manyuagashe** [comment]
Passwords are kinda gone entirely so I think that fix is unnecessary? then police and admin pagination are now both fixed and both properly responsive, and i had to make some changes to docker compose and stuff that maybe nick can look over instead while you check for the rest of my PR.

**Review by notvasub — APPROVED** [review]
LGTM
